services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-container
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - pg-network

volumes:
  pgvector-data:

networks:
  pg-network:
    driver: bridge